paths:
    scripts: '/project2/jnovembre/ccliu/backgroundSelection/scripts'
    data: '/project2/jnovembre/ccliu/backgroundSelection/data'
    output: '/project2/jnovembre/ccliu/backgroundSelection/output'
