path:
    script: '/project2/jnovembre/ccliu/backgroundSelection/script'
    data: '/project2/jnovembre/ccliu/backgroundSelection/data'
    output: '/project2/jnovembre/ccliu/backgroundSelection/output'
params:
    standard_N: 5000
    base_mutation_rate: 1e-7
    genome_length: 5e5